//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaZero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        public string Key { get; set; }
        public int Value { get; set; }
        public Nullable<System.DateTime> ExpireAt { get; set; }
        public long Id { get; set; }
    }
}
